#!/bin/sh
set -e
package_name=disable-journald
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/etc/systemd/journald.conf"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/etc/systemd/journald.conf"
;;
esac
exit 0
